### PR TITLE
Degraded flow for resources (audio)

### PR DESCRIPTION
**Pull request by tomcrane**

### CODE REVIEW

**Comment by tomcrane** [comment]
@fractos 

This is ready to be dockerised and deployed (thought I'd alpinised this but must have been something else - should do that at some point).

I need to merge the client PR at the same time:
https://github.com/digirati-co-uk/iiif-auth-client/pull/8

...so we need to synchronise activity.

**Comment by tomcrane** [comment]
@fractos I added an extra audio file to this and updated some config

**Comment by fractos** [comment]
@tomcrane Is this still relevant?

**Comment by tomcrane** [comment]
Yeah, this is the current deployed version on https://iiifauth.digtest.co.uk/ 

I would like to get some time to tidy it up a little more.

**Pull request merged**
